import = ["/home/james/.config/alacritty/themes/kanagawa.toml"]

[bell]
animation = "EaseOut"
color = "#4f304f"
duration = 800

[font]
size = 9.0

[font.bold]
family = "iosevka slab"
style = "Bold"

[font.italic]
family = "iosevka slab"
style = "Italic"

[font.normal]
family = "iosevka curly slab"

[shell]
program = "/bin/fish"
